trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: '<YOUR-AZURE-SERVICE-CONNECTION-NAME>'
  appName: '<YOUR-APP-SERVICE-NAME>'
  resourceGroupName: '<YOUR-RESOURCE-GROUP-NAME>'
  packagePath: '$(System.DefaultWorkingDirectory)'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Install and Build'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
      replaceExistingArchive: true

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(azureSubscription)'
      appName: '$(appName)'
      package: '$(Build.ArtifactStagingDirectory)/app.zip'
